// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBA6dLZhIRHaO17OtDZhRmqMhx_t3ButAE',
    appId: '1:805269469998:web:226f3608335ffcc924d8bf',
    messagingSenderId: '805269469998',
    projectId: 'fir-project-1-8086d',
    authDomain: 'fir-project-1-8086d.firebaseapp.com',
    storageBucket: 'fir-project-1-8086d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaRSbp_jrsSpoJASaSTy8wBt_pHX2_ttc',
    appId: '1:805269469998:android:35d85e64a660add624d8bf',
    messagingSenderId: '805269469998',
    projectId: 'fir-project-1-8086d',
    storageBucket: 'fir-project-1-8086d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmjlH3NOL8Z63s6--JqqXezj7alZ5pL74',
    appId: '1:805269469998:ios:314c472e073a49cb24d8bf',
    messagingSenderId: '805269469998',
    projectId: 'fir-project-1-8086d',
    storageBucket: 'fir-project-1-8086d.appspot.com',
    iosClientId: '805269469998-33ipc8mgon65mao7vmjiuhspccaou9i4.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseProject1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmjlH3NOL8Z63s6--JqqXezj7alZ5pL74',
    appId: '1:805269469998:ios:314c472e073a49cb24d8bf',
    messagingSenderId: '805269469998',
    projectId: 'fir-project-1-8086d',
    storageBucket: 'fir-project-1-8086d.appspot.com',
    iosClientId: '805269469998-33ipc8mgon65mao7vmjiuhspccaou9i4.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseProject1',
  );
}