include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    library_private_types_in_public_api: ignore
  exclude:
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**

linter:
  rules:
    always_declare_return_types: true
    avoid_dynamic_calls: true
    directives_ordering: true
    prefer_const_constructors: true
    prefer_final_locals: true
    sort_child_properties_last: true
    unawaited_futures: true
