// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChfiahLw8RLA0ktx8huLlgcygozZ_PrOU',
    appId: '1:281065592471:web:6f14332c615abb98a3bbd2',
    messagingSenderId: '281065592471',
    projectId: 'nstrackerapp',
    authDomain: 'nstrackerapp.firebaseapp.com',
    storageBucket: 'nstrackerapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPksvuWDjGCym1WoQyQZrjMqn4cYYuigE',
    appId: '1:281065592471:android:5e277fd84d9b84d2a3bbd2',
    messagingSenderId: '281065592471',
    projectId: 'nstrackerapp',
    storageBucket: 'nstrackerapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQ4wIZnYfeHQyHtiUrYLuTK4CKXBhBMB8',
    appId: '1:281065592471:ios:0c75bb6268a5bf8ba3bbd2',
    messagingSenderId: '281065592471',
    projectId: 'nstrackerapp',
    storageBucket: 'nstrackerapp.appspot.com',
    iosClientId: '281065592471-u9gm3sus681f5l4ip1qbbarmcjv34v28.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseProject2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQ4wIZnYfeHQyHtiUrYLuTK4CKXBhBMB8',
    appId: '1:281065592471:ios:0c75bb6268a5bf8ba3bbd2',
    messagingSenderId: '281065592471',
    projectId: 'nstrackerapp',
    storageBucket: 'nstrackerapp.appspot.com',
    iosClientId: '281065592471-u9gm3sus681f5l4ip1qbbarmcjv34v28.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseProject2',
  );
}
